### ISSUE TITLE
Publish GitSpace v2 Golang Package

### ISSUE THREAD

**Issue by davfive** [davfive/gitspaces.golang#24]
## Tasks
- [x]  Publish Golang Package
    - [x] Publish to https://pkg.go.dev/
    - [x] Verify README visible on https://pkg.go.dev/
    - [x] Verify `go install github.com/davfive/gitspaces/v2@latest`

## Summary

Publish gitspaces to https://pkg.go.dev/ to ensure idiomatic golang deployment.

## Details

See https://go.dev/doc/modules/publishing for publishing guide.
