### ISSUE TITLE
GitSpaces v2 Tests

### ISSUE THREAD

**Issue by davfive** [davfive/gitspaces.golang#26]
## Tasks

- [ ] Write tests for gitspaces package
- [ ] Write tests for helper package
- [ ] Write tests for cmd package

## Summary

Write tests that will be run via 
* local pre-commit
* GitActions pre-packaging
