### ISSUE TITLE
GitSpaces v2 CI/CD Actions

### ISSUE THREAD

**Issue by davfive** [davfive/gitspaces.golang#27]
## Tasks
- Actions
   - [ ] create an action to auto test pre-merge
   - [ ] create a release/package for mac and windows (run manually)
   - [ ] create an action to push release to https://pkg.go.dev/
