### ISSUE TITLE
GitSpace v2 Documentation

### ISSUE THREAD

**Issue by davfive** [davfive/gitspaces.golang#4]
## Tasks
- Sections
    - [x] What is GitSpaces
    - [x] Project Roadmap
    - [x] Quick Start Guide
    - [ ] Documentation
        - [x] Command
        - [ ] Initial Setup
        - [ ] Examples
    - [x] GitSpace Structure
- Stardust
   - [x] Add page banner

## Summary

Write the v2 documentation with the intent that unless I add new features or change behaviors, I won't need to update it.

## Details
See [Beautify Docs](https://github.com/matheusfelipeog/beautiful-docs) on GitHub for great advice.

### README files I like
- [Backstage.io](https://github.com/backstage/backstage/blob/master/README.md)
- [Cobra](https://github.com/spf13/cobra)

**Comment by davfive** [comment]
Commit was missing unsaved README.md file updates.

**Comment by davfive** [comment]
Commit 400476f adds in the unsaved changes to README file
